%%%% This code generates a Customized G-code for Uniform Hexagonal and Diamond frame structures %%%%
%%%% Customized tool-path is generated by defining a continuous nodal path with uniform flow rate %%
%%%% Written By Dhanashri Desai (3rd year,MTech(R),ME,IISc) during 1 Aug'22 to 10 Oct'22 for the fulfillment of MTech(R) Thesis %%%%
%%%% Modified by Jaydeep Pawar (2nd year,MTech,CSA,IISc) for generalization w.r.t. no of cells %%%%

%% Main function
%%% This function contains the parametric data for unit cell in the cellular frame structure %%%
%%% which are passed as argumemnts to user-defined functions to generate eventually the G-code file %%%

clear; clc; close all; % Housekeeping commands
tCell=2; theta=60; rho_rel=0.2; % parameters of unit cell and relative density
nCellH=3; nCellV=3; % no of cells in horizontal and vertical direction 
CellType='StretchDominatedDiamond'; % StretchDominatedDiamond BendingDominatedHexagon
E0=5.87; dLdE=60; % initial feed rate (end value of prime tower Gcode) and uniform rate at which motor feed increases
nLayer=8; % no. of layers to be printed

% generate grid of nodes and elements
[LCell,Lh,Lv,nelem,nnodes,nodeID,nx,ny,Nrows,Ncolumns,LhDomain,LvDomain] = Generate2DGrid(CellType,nCellH,nCellV,tCell,rho_rel,theta);
% generate continuous nodal path
[NodalPath] = GenerateNodalPath(CellType,nnodes,nCellH,nCellV);
% generate uniform flow rate data according to nodal path
[E,nExtrusion] = GenerateFeedRate(CellType,E0,nelem,dLdE,LCell,Lv,LhDomain,LvDomain,nCellH,nCellV,Nrows,nLayer);
% generate G-code file
WriteToFile(CellType,NodalPath,nx,ny,E,nCellH,nCellV,nExtrusion,nLayer);